### ISSUE TITLE
location.href not valid in function updateBlame()

### ISSUE THREAD

**Issue by ccskoba** [takezoe/gitbucket#864] opened 2015-08-06 16:12 UTC
src/main/twirl/gitbucket/core/repo/blob.scala.html
```
154  function updateBlame(){
155	    var m = /^\/(blame|blob)(\/.*)$/.exec(location.href.substring(repository.length));
```

"location.href" is like a "http://xxxxx/path/name".
so, it should be "location.pathname".

Best Regards,

**Comment by pibi** [comment] 2015-08-10 13:56
Should work if you set the Base URL on the System Settings. 

This bug is a duplicate of #781

**Closed** 2015-08-23 17:40 UTC
Labels: bug
