### ISSUE TITLE
Opening svg for display very slow and displays jquery popup

### ISSUE THREAD

**Issue by 3-O** [takezoe/gitbucket#741] opened 2015-05-03 08:11 UTC
Just navigating to the file leads to the following situation where the pretty printed svg source is eventually displayed but after a very long time (svg file has 2341 lines).

![gitb1](https://cloud.githubusercontent.com/assets/12143150/7444306/6ceba79c-f17c-11e4-97a1-2f2795379255.png)
![gitb2](https://cloud.githubusercontent.com/assets/12143150/7444307/6cee0bc2-f17c-11e4-9f4f-3eaca1317498.png)
![gitb3](https://cloud.githubusercontent.com/assets/12143150/7444308/6cf0b73c-f17c-11e4-89dc-4ccdd5ad2c25.png)

**Comment by takezoe** [comment] 2015-05-06 01:41
@3-O Check my comment at https://github.com/takezoe/gitbucket/issues/738#issuecomment-99283389
I think the cause of these issues is same.

**Comment by 3-O** [comment] 2015-05-06 06:19
Indeed, likely same or related cause. However outcome is different: 
- normal display: only slow;
- raw display: get an error.

**Comment by takezoe** [comment] 2015-05-06 06:55
OK, I will try again. This issue might be merged to #738.

**Comment by takezoe** [comment] 2015-05-10 08:37
Merged to #738

**Closed by takezoe** 2015-05-10 08:37 UTC
Labels: duplicate
