### ISSUE TITLE
Old dependency

### ISSUE THREAD

**Issue by alexove** [takezoe/gitbucket#573] opened 2014-12-12 12:24 UTC
I installed gitbucket on openshift.com but I get a NotClassFoundException issue with /com/sun/net/ssl/internal/ssl/Provider.
I resolved putting the jar com.sun.net.ssl.jar inside the WAR file manually
Maybe is time to upgrade this dep.
Nice work takezoe :-)

**Comment by takezoe** [comment] 2015-01-01 09:11
Duplicate of #473

**Closed by takezoe** 2015-01-01 09:11 UTC
Labels: duplicate
